kind: Deployment
apiVersion: apps/v1
metadata:
  name: teste2e
  namespace: aarshgo
  labels:
    app: test-aarsh-go
  annotations:
    deployment.kubernetes.io/revision: '1'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-aarsh-go
  template:
    metadata:
      labels:
        app: test-aarsh-go
    spec:
      containers:
        - name: goaarsh
          image: aarshshah33/teste2e:latest
          ports:
            - name: heybro
              containerPort: 8080
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
